[package]
name = "quyaml"
version = "0.1.0"
authors = ["Vitaliy Pavlikov <warhotpoint@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "^0.4"
clap = { git = "https://github.com/clap-rs/clap" }